version: '3'
services:
  face_count:
    build:
      context: .
      dockerfile: DockerFile
    container_name: face_count
    ports:
      - "5000:5000"
    volumes:
      - ./static/processed:/app/static/processed
    environment:
      - MODEL_PATH=/app/saved_model
      - FLASK_ENV="development"
